[2022-04-25 11:18:02.137129][Error] There was error occured in file /root/EqualDB/EqualDB.py at line 121.
