[2022-04-04 09:59:21.234173][Error] There was error occured in file /root/Jessise-DB/JessiseDB.py at line 84.
